// This file is used to store error codes
// The error codes are used to identify the error and should match the codes defined in the backend

export const ERROR_CODES = {
	EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
	INVALID_PASSWORD: "INVALID_PASSWORD",
	USER_NOT_FOUND: "USER_NOT_FOUND",
	INVALID_OTP: "INVALID_OTP",
	PASSWORD_EXPIRED: "PASSWORD_EXPIRED",
	PASSWORD_EXPIRING_SOON: "PASSWORD_EXPIRING_SOON",
	PASSWORD_CHANGE_REQUIRED: "PASSWORD_CHANGE_REQUIRED",
	ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
	ACCOUNT_LOCKED_RESET_REQUIRED: "ACCOUNT_LOCKED_RESET_REQUIRED",
	RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
	VERIFY_ROW_LIMIT_EXCEEDED: "VERIFY_ROW_LIMIT_EXCEEDED",
	VERIFY_RETENTION_SWEEP_ACTIVE: "VERIFY_RETENTION_SWEEP_ACTIVE",
} as const;

export type TErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
